# Generated by Django 6.1 on 2026-08-23 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='رقم الفاتورة')),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='الباركود')),
                ('customer_name', models.CharField(max_length=120, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('hard_disk_type', models.CharField(choices=[('hdd_35', 'HDD 3.5'), ('hdd_25', 'HDD 2.5'), ('ssd', 'SSD'), ('nvme', 'NVMe'), ('external', 'هارد خارجي'), ('usb', 'فلاش USB'), ('memory_card', 'كرت ذاكرة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الهارد')),
                ('status', models.CharField(choices=[('received', 'تم الاستلام'), ('finished', 'فنش'), ('completed', 'خلص'), ('has_problems', 'في مشاكل')], default='received', max_length=20, verbose_name='حالة المتابعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'فاتورة / عملية',
                'verbose_name_plural': 'الفواتير / العمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'تم الاستلام'), ('finished', 'فنش'), ('completed', 'خلص'), ('has_problems', 'في مشاكل')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='jobs.job')),
            ],
            options={
                'verbose_name': 'سجل حالة',
                'verbose_name_plural': 'سجل الحالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
