# Generated by Django 6.1.1 on 2026-09-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attached_equipment',
            field=models.TextField(blank=True, help_text='مثال: كيبل، علبة، شنطة', verbose_name='الملحقات المرافقة'),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='إيميل العميل'),
        ),
        migrations.AddField(
            model_name='job',
            name='device_model',
            field=models.CharField(blank=True, help_text='مثال: Western Digital، Toshiba', max_length=120, verbose_name='الموديل / الماركة'),
        ),
        migrations.AddField(
            model_name='job',
            name='inspection_notes',
            field=models.TextField(blank=True, help_text='ملاحظات الموظف بعد الفحص - منفصلة عن كلام العميل', verbose_name='ملاحظات الفحص'),
        ),
        migrations.AddField(
            model_name='job',
            name='problem',
            field=models.TextField(blank=True, help_text='نص حر - يلي قاله العميل عن المشكلة (Customer Comments)', verbose_name='المشكلة (كلام العميل)'),
        ),
        migrations.AddField(
            model_name='job',
            name='ready_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تبليغ العميل بالجاهزية'),
        ),
        migrations.AddField(
            model_name='job',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='الرقم التسلسلي S/N'),
        ),
    ]
