# Generated by Django 6.1.1 on 2026-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_attached_equipment_job_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_report',
            field=models.CharField(blank=True, choices=[('agree', 'موافق على السعر'), ('wait_client', 'بانتظار رد العميل'), ('finished', 'خلص / جاهز للاستلام')], max_length=20, verbose_name='قرار العميل على السعر'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ / البحث عن قطع'), ('finished', 'انتهى الإصلاح')], max_length=20, verbose_name='حالة الشغل (بعد الموافقة)'),
        ),
    ]
