# Generated by Django 6.1.1 on 2026-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_client_report_job_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='field_name',
            field=models.CharField(choices=[('status', 'الحالة العامة'), ('client_report', 'قرار العميل'), ('work_status', 'حالة الشغل')], default='status', max_length=20, verbose_name='الحقل المتغيّر'),
        ),
    ]
