# Generated by Django 6.1.1 on 2026-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_statuslog_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الإجمالي'),
        ),
        migrations.AddField(
            model_name='job',
            name='report_flag',
            field=models.CharField(blank=True, choices=[('none', 'بدون'), ('no_spare_parts', 'لا يوجد قطع غيار'), ('send_out_china', 'يُرسل للصين')], default='none', max_length=20, verbose_name='علم تقرير الفحص'),
        ),
    ]
