# Generated by Django 6.1.1 on 2026-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_quotation_quotationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_client_alert_days', models.PositiveIntegerField(default=1, verbose_name='مهلة تنبيه انتظار العميل (بالأيام)')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
