# Generated by Django 6.1.1 on 2026-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم الفعلي للعميل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client_report',
            field=models.CharField(blank=True, choices=[('agree', 'موافق على السعر'), ('wait_client', 'بانتظار رد العميل'), ('finished', 'خلص / جاهز للاستلام'), ('rejected', 'مرفوض من العميل')], max_length=20, verbose_name='قرار العميل على السعر'),
        ),
    ]
