# Generated by Django 6.1.1 on 2026-09-10 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_delivered_at_alter_job_client_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='رقم التليفون')),
                ('role', models.CharField(default='IT Employee', max_length=120, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(default='Data Recovery & Forensic Analysis', max_length=120, verbose_name='القسم')),
                ('photo', models.FileField(blank=True, upload_to='employee_photos/', verbose_name='الصورة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ملف الموظف',
                'verbose_name_plural': 'ملفات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_attachments/%Y/%m/', verbose_name='الملف')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'مرفقات القضية',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
