# Generated by Django 6.1.1 on 2026-09-13 15:21

from django.db import migrations, models


def merge_finished_into_completed(apps, schema_editor):
    """«فنش» و«خلص» كانوا نفس المعنى — منوحّدهن على completed.

    بينطبق على حقل status فقط. work_status و client_report عندهن
    قيمة finished مستقلة وإلها معنى مختلف، فما منلمسهن.
    """
    Job = apps.get_model("jobs", "Job")
    StatusLog = apps.get_model("jobs", "StatusLog")
    Job.objects.filter(status="finished").update(status="completed")
    StatusLog.objects.filter(status="finished").update(status="completed")


def split_completed_back(apps, schema_editor):
    """تراجع: ما منقدر نعرف مين كان finished قبل الدمج، فمنخلّيهن completed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_employee_profile_and_attachments'),
    ]

    operations = [
        migrations.RunPython(
            merge_finished_into_completed,
            split_completed_back,
        ),
        migrations.AlterField(
            model_name='job',
            name='client_report',
            field=models.CharField(blank=True, choices=[('agree', 'Agree'), ('wait_client', 'Wait client'), ('finished', 'Ready'), ('rejected', 'Rejected')], max_length=20, verbose_name='قرار العميل على السعر'),
        ),
        migrations.AlterField(
            model_name='job',
            name='report_flag',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('no_spare_parts', 'No spare parts'), ('send_out_china', 'Send to China')], default='none', max_length=20, verbose_name='علم تقرير الفحص'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('completed', 'Completed'), ('has_problems', 'Has problems')], default='received', max_length=20, verbose_name='حالة المتابعة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Done')], max_length=20, verbose_name='حالة الشغل (بعد الموافقة)'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('completed', 'Completed'), ('has_problems', 'Has problems')], max_length=20),
        ),
    ]
