# Generated by Django 6.1.1 on 2026-09-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_client_report_alter_job_report_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNumberBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='معرّف الجهاز')),
                ('block_start', models.PositiveIntegerField(verbose_name='بداية المدى')),
                ('block_size', models.PositiveIntegerField(default=50, verbose_name='حجم المدى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_blocks', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مدى أرقام جهاز',
                'verbose_name_plural': 'مدايات أرقام الأجهزة',
                'ordering': ['block_start'],
            },
        ),
    ]
