# Generated by Django 6.1.1 on 2026-09-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_clear_legacy_creation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenumberblock',
            name='block_size',
            field=models.PositiveIntegerField(default=1000, verbose_name='حجم المدى'),
        ),
    ]
