#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NGROK_URL_FILE="$ROOT_DIR/.ngrok_url"
BACKEND_PORT="8000"
NGROK_API="http://127.0.0.1:4040/api/tunnels"

cd "$ROOT_DIR"

echo "Starting ngrok tunnel for the Django backend on port ${BACKEND_PORT}."
echo

if ! command -v ngrok >/dev/null 2>&1; then
  echo "ngrok is not installed or not in PATH."
  echo "Install it from https://ngrok.com/download"
  echo "Then run: ngrok config add-authtoken YOUR_TOKEN"
  exit 1
fi

if ! curl -sf "http://127.0.0.1:${BACKEND_PORT}/api/health/" >/dev/null 2>&1 \
  && ! curl -sf "http://127.0.0.1:${BACKEND_PORT}/admin/" >/dev/null 2>&1; then
  echo "Django does not appear to be running on http://127.0.0.1:${BACKEND_PORT}"
  echo "Start it first, for example:"
  echo "  source .venv/bin/activate"
  echo "  python manage.py runserver 127.0.0.1:${BACKEND_PORT}"
  exit 1
fi

fetch_ngrok_https_url() {
  python3 - <<'PY'
import json
import urllib.request

try:
    with urllib.request.urlopen("http://127.0.0.1:4040/api/tunnels", timeout=2) as response:
        data = json.load(response)
except Exception:
    raise SystemExit(1)

for tunnel in data.get("tunnels", []):
    url = tunnel.get("public_url") or ""
    if url.startswith("https://"):
        print(url)
        raise SystemExit(0)

raise SystemExit(1)
PY
}

write_runtime_config() {
  local public_url="$1"
  python3 - "$ROOT_DIR" "$public_url" <<'PY'
import sys
from pathlib import Path
from urllib.parse import urlparse

root = Path(sys.argv[1])
public_url = sys.argv[2].rstrip("/")
parsed = urlparse(public_url)
host = parsed.netloc
api_base = f"{public_url}/api/"

env_path = root / ".env"
values = {}
if env_path.exists():
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()

values["DJANGO_DEBUG"] = values.get("DJANGO_DEBUG") or "1"
values["NGROK_PUBLIC_URL"] = public_url
values["NGROK_HOST"] = host
values["API_BASE_URL"] = api_base

hosts = [item.strip() for item in values.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if item.strip()]
for item in ("localhost", "127.0.0.1", host):
    if item not in hosts:
        hosts.append(item)
values["DJANGO_ALLOWED_HOSTS"] = ",".join(hosts)

origins = [
    item.strip()
    for item in values.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000",
    ).split(",")
    if item.strip()
]
if public_url not in origins:
    origins.append(public_url)
values["DJANGO_CSRF_TRUSTED_ORIGINS"] = ",".join(origins)

preferred = [
    "DJANGO_SECRET_KEY",
    "DJANGO_DEBUG",
    "DJANGO_ALLOWED_HOSTS",
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "NGROK_PUBLIC_URL",
    "NGROK_HOST",
    "API_BASE_URL",
]
lines = []
seen = set()
for key in preferred:
    if key in values:
        lines.append(f"{key}={values[key]}")
        seen.add(key)
for key, value in values.items():
    if key not in seen:
        lines.append(f"{key}={value}")
env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

runtime_path = root / "config" / "ngrok_runtime.py"
runtime_path.write_text(
    "# Generated by start_ngrok.sh. Do not edit by hand.\n"
    f'NGROK_PUBLIC_URL = "{public_url}"\n'
    f'NGROK_HOST = "{host}"\n'
    f'API_BASE_URL = "{api_base}"\n',
    encoding="utf-8",
)

flutter_config = root / "data_recovery_app" / "lib" / "core" / "api_config.dart"
flutter_config.write_text(
    "class ApiConfig {\n"
    "  // Generated by start_ngrok.sh.\n"
    f"  static const String publicUrl = '{public_url}';\n"
    f"  static const String apiBaseUrl = '{api_base}';\n"
    "}\n",
    encoding="utf-8",
)

print(api_base)
PY
}

EXISTING_URL="$(fetch_ngrok_https_url 2>/dev/null || true)"
if [[ -n "${EXISTING_URL}" ]]; then
  echo "An ngrok tunnel is already running."
else
  echo "Launching ngrok..."
  ngrok http "${BACKEND_PORT}" >/tmp/ngrok-01-data-recovery.log 2>&1 &
  NGROK_PID=$!

  for _ in $(seq 1 20); do
    sleep 1
    EXISTING_URL="$(fetch_ngrok_https_url 2>/dev/null || true)"
    if [[ -n "${EXISTING_URL}" ]]; then
      break
    fi
    if ! kill -0 "${NGROK_PID}" 2>/dev/null; then
      echo "ngrok exited unexpectedly. Last log lines:"
      tail -n 20 /tmp/ngrok-01-data-recovery.log || true
      echo
      echo "If this is a new install, add your authtoken:"
      echo "  ngrok config add-authtoken YOUR_TOKEN"
      exit 1
    fi
  done
fi

if [[ -z "${EXISTING_URL}" ]]; then
  echo "Could not read the public ngrok URL from ${NGROK_API}"
  echo "Open http://127.0.0.1:4040 in a browser and copy the HTTPS URL."
  exit 1
fi

API_URL="$(write_runtime_config "${EXISTING_URL}")"
printf '%s\n' "${EXISTING_URL}" > "${NGROK_URL_FILE}"

echo
echo "Backend is reachable at:"
echo "  ${EXISTING_URL}"
echo "API base URL for the Flutter app:"
echo "  ${API_URL}"
echo
echo "Wrote the URL dynamically to:"
echo "  ${ROOT_DIR}/.env"
echo "  ${ROOT_DIR}/config/ngrok_runtime.py"
echo "  ${ROOT_DIR}/data_recovery_app/lib/core/api_config.dart"
echo "  ${NGROK_URL_FILE}"
echo
echo "Keep this ngrok process running while testers use the app."
echo "Inspect traffic at http://127.0.0.1:4040"
echo
echo "Next: run ./build_app.sh and choose ngrok when asked."
echo "If Flutter is already running, do a hot restart so it picks up the new API URL."
