# Generated by Django 6.1.1 on 2026-10-04 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='للتعريف بس (مثلاً اسم العميل أو الجهة) — مش مرتبط بحساب', max_length=120, verbose_name='الاسم')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='التوكن')),
                ('image_quota', models.PositiveIntegerField(verbose_name='عدد الصور المسموح بها كل فترة')),
                ('period', models.CharField(choices=[('daily', 'يومياً'), ('weekly', 'أسبوعياً'), ('monthly', 'شهرياً')], default='monthly', max_length=10, verbose_name='الفترة')),
                ('images_used', models.PositiveIntegerField(default=0, verbose_name='المستهلك بالفترة الحالية')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بداية الفترة الحالية')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'توكن API',
                'verbose_name_plural': 'توكنات API',
                'ordering': ['-created_at'],
            },
        ),
    ]
